---
  - hosts: azure
    become: true
    gather_facts: false

    tasks:
    - name: Se instala git
      apt:
        name: ['git']
        state: present
        update_cache: yes

    - name: Se instala curl
      apt:
        name: ['curl']
        state: present
        update_cache: yes

    

    - name: Se instala NodeJS Process Manager (PM2)
      npm: name=pm2 executable=/usr/bin/npm global=yes

    - name: Se descarga GitHub del repositorio de Jose Ramón Trillo Vílchez
      git:
        repo: https://github.com/jrtrillo/proyecto_cc.git
        dest: ./proyecto_cc

    - name: Se instala las dependencias del package.json
      raw: cd proyecto_cc; npm install

    - name: Se descarga NodeJS
      become: yes
      shell: curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
      args: 
        warn: no

    - name: Se instala NodeJS
      become: yes
      apt: pkg=nodejs state=latest

    
    