---
  - hosts: ubuntu1

    tasks:
    - name: Instala git
      become: yes
      apt: pkg=git state=present
    
    - name: Instala curl 
      become: yes
      apt: pkg=curl state=latest
      
    - name: Se descarga NodeJS
      become: yes
      shell: curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
      args: 
        warn: no

     - name: Se instala NodeJS
      become: yes
      apt: pkg=nodejs state=latest

    - name: Se descarga GitHub del repositorio de Jose Ramón Trillo Vílchez
      git:
        repo: https://github.com/jrtrillo/proyecto_cc.git
        dest: ./proyecto_cc

    - name: Se instala las dependencias del package.json
      raw: cd proyecto_cc; npm install

    - name: Se instala NodeJS Process Manager (PM2)
      npm: name=pm2 executable=/usr/bin/npm global=yes

    
